.TH SOSREPORT 1 "Tue Feb 20 2007"
.SH NAME
sosreport \- Generate debugging information for this system
.SH SYNOPSIS
.B sosreport
[-a|--alloptions] [-f|--fastoptions] [-g|--gatheronly] 
          [-l|--list-plugins] [-n|--noplugin \fIplugin-name\fR] 
          [-o|--onlyplugin \fIplugin-name\fR]
          [-v|--verbose [...]] [-m|--multithreaded]
.SH DESCRIPTION
\fBsosreport\fR generates a compressed tarball of debugging information 
for the system it is run on that can be sent to technical support
reps that will give them a more complete view of the overall system
status.
.SH OPTIONS
.TP
.B \-a, \--alloptions
Enable all options for all loaded plugins
.TP
.B \-f, \--fastoptions
Enable all options marked as "fast" for loaded plugins.  This will
reduce running time while still gathering helpful information, but
you may be asked to re-run later with some or all "slow" options
enabled depending on the specific issue.
.TP
.B \-g, \--gatheronly
Gather the diagnostic data and bundle it up, but do not attempt to
send it to any support site.  This option currently has no effect as
sosreport currently does not support report transmission.
.TP
.B \-l, \--list-plugins
List available plugins
.TP
.B \-n, \--noplugin
Do not load specified plugin(s)
.TP
.B \-o, \--onlyplugin
Load only the specified plugin(s), all otherplugins should be disabled
.TP
.B \-v, \--verbose
Increase the verbosity of the output as sosreport is running.  This option
can be specified more than once.
.TP
.B \-m, \--multithreaded
Enable a multithreaded collection and analysis of the sosreport data.  Please
note that this option is experimental and is known to have intermittent issues.
.SH BUGS
The multithreaded option can fail intermittently, please use it with care.
.SH AUTHORS
.nf
Steve Conklin <sconklin@redhat.com>
John Berninger <jwb@redhat.com>
Navid Sheikhol-Eslami <navid@redhat.com>
Pierre Amadio <pamadio@redhat.com>
.fi
