downstream_package_name: sos
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-rawhide-x86_64
  trigger: pull_request
specfile_path: sos.spec
synced_files:
- sos.spec
- .packit.yaml
upstream_package_name: sos
