upstream_project_url: https://github.com/sosreport/sos
specfile_path: sos.spec
downstream_package_name: sos
upstream_package_name: sos

files_to_sync:
  - sos.spec
  - .packit.yaml

srpm_build_deps:
  - python3-devel
  - gettext

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
      - fedora-all-ppc64le
      - fedora-all-s390x

notifications:
  pull_request:
    successful_build: true
