"""
setup.py - Setup package with the help from Python's DistUtils
"""

from distutils.core import setup

setup(
	name = 'sos',
    version = '1.8',
    author = 'Adam Stokes',
    author_email = 'ajs@redhat.com',
    url = 'http://fedorahosted.org/sos',
    description = 'SOS - son of sysreport',
	packages = ['sos', 'sos.plugins'],
	scripts = [],
	package_dir = {'': 'lib',},
	data_files = [ ('/etc', [ 'sos.conf']), 
    ('/usr/sbin', ['sosreport', 'extras/sysreport/sysreport.legacy']), 
    ('/usr/bin', ['extras/rh-upload-core']), 
    ('/usr/share/sysreport', ['extras/sysreport/text.xsl', 'extras/sysreport/functions', 'extras/sysreport/sysreport-fdisk']), 
    ('/usr/share/man/man1', ['sosreport.1.gz']),
	('/usr/share/locale/af/LC_MESSAGES', ['locale/af/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/am/LC_MESSAGES', ['locale/am/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ar/LC_MESSAGES', ['locale/ar/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/as/LC_MESSAGES', ['locale/as/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/be/LC_MESSAGES', ['locale/be/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/bg/LC_MESSAGES', ['locale/bg/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/bn/LC_MESSAGES', ['locale/bn/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/bn_IN/LC_MESSAGES', ['locale/bn_IN/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/bs/LC_MESSAGES', ['locale/bs/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ca/LC_MESSAGES', ['locale/ca/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/cs/LC_MESSAGES', ['locale/cs/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/cy/LC_MESSAGES', ['locale/cy/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/da/LC_MESSAGES', ['locale/da/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/de/LC_MESSAGES', ['locale/de/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/el/LC_MESSAGES', ['locale/el/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/en/LC_MESSAGES', ['locale/en/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/en_GB/LC_MESSAGES', ['locale/en_GB/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/es/LC_MESSAGES', ['locale/es/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/et/LC_MESSAGES', ['locale/et/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/eu_ES/LC_MESSAGES', ['locale/eu_ES/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/fa/LC_MESSAGES', ['locale/fa/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/fi/LC_MESSAGES', ['locale/fi/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/fr/LC_MESSAGES', ['locale/fr/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/gl/LC_MESSAGES', ['locale/gl/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/gu/LC_MESSAGES', ['locale/gu/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/he/LC_MESSAGES', ['locale/he/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/hi/LC_MESSAGES', ['locale/hi/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/hr/LC_MESSAGES', ['locale/hr/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/hu/LC_MESSAGES', ['locale/hu/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/hy/LC_MESSAGES', ['locale/hy/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/id/LC_MESSAGES', ['locale/id/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ilo/LC_MESSAGES', ['locale/ilo/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/is/LC_MESSAGES', ['locale/is/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/it/LC_MESSAGES', ['locale/it/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ja/LC_MESSAGES', ['locale/ja/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ka/LC_MESSAGES', ['locale/ka/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/kn/LC_MESSAGES', ['locale/kn/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ko/LC_MESSAGES', ['locale/ko/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ku/LC_MESSAGES', ['locale/ku/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/lo/LC_MESSAGES', ['locale/lo/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/lt/LC_MESSAGES', ['locale/lt/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/lv/LC_MESSAGES', ['locale/lv/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/mk/LC_MESSAGES', ['locale/mk/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ml/LC_MESSAGES', ['locale/ml/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/mr/LC_MESSAGES', ['locale/mr/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ms/LC_MESSAGES', ['locale/ms/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/my/LC_MESSAGES', ['locale/my/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/nb/LC_MESSAGES', ['locale/nb/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/nl/LC_MESSAGES', ['locale/nl/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/nn/LC_MESSAGES', ['locale/nn/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/no/LC_MESSAGES', ['locale/no/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/nso/LC_MESSAGES', ['locale/nso/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/or/LC_MESSAGES', ['locale/or/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/pa/LC_MESSAGES', ['locale/pa/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/pl/LC_MESSAGES', ['locale/pl/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/pt/LC_MESSAGES', ['locale/pt/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/pt_BR/LC_MESSAGES', ['locale/pt_BR/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ro/LC_MESSAGES', ['locale/ro/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ru/LC_MESSAGES', ['locale/ru/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/si/LC_MESSAGES', ['locale/si/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/sk/LC_MESSAGES', ['locale/sk/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/sl/LC_MESSAGES', ['locale/sl/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/sq/LC_MESSAGES', ['locale/sq/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/sr/LC_MESSAGES', ['locale/sr/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/sr@latin/LC_MESSAGES', ['locale/sr@latin/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/sv/LC_MESSAGES', ['locale/sv/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ta/LC_MESSAGES', ['locale/ta/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/te/LC_MESSAGES', ['locale/te/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/th/LC_MESSAGES', ['locale/th/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/tr/LC_MESSAGES', ['locale/tr/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/uk/LC_MESSAGES', ['locale/uk/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/ur/LC_MESSAGES', ['locale/ur/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/vi/LC_MESSAGES', ['locale/vi/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/zh_CN/LC_MESSAGES', ['locale/zh_CN/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/zh_TW/LC_MESSAGES', ['locale/zh_TW/LC_MESSAGES/sos.mo']),
	('/usr/share/locale/zu/LC_MESSAGES', ['locale/zu/LC_MESSAGES/sos.mo']),
	]
)
