.TH SOSREPORT 1 "Tue Feb 20 2007"
.SH NAME
sosreport \- Generate debugging information for this system
.SH SYNOPSIS
.B sosreport
          [-l|--list-plugins]\fR
          [-n|--skip-plugins plugin-names] [-e|--enable-plugins plugin-names] [-o|--only-plugins plugin-names]\fR
          [-a|--alloptions] [-v|--verbose]
          [--no-multithread] [--no-progressbar]
.SH DESCRIPTION
\fBsosreport\fR generates a compressed tarball of debugging information 
for the system it is run on that can be sent to technical support
reps that will give them a more complete view of the overall system
status.
.SH OPTIONS
.TP
.B \-l, \--list-plugins
This will list all available plugins showing which ones will be enabled by the current configuration. It will also show all plugin options which can be 
modified using the -k option (see below).
.TP
.B \-n, --skip-plugins PLUGNAME[,PLUGNAME]
Do not load specified plugin(s). To specify multiple plugins, separate them with a comma.
.TP
.B \-e, --enable-plugins PLUGNAME[,PLUGNAME]
Enable the specified plugin(s). To specify multiple plugins, separate them with a comma.
.TP
.B \-o, --only-plugins PLUGNAME[,PLUGNAME]
Enable the specified plugin(s) only (all other plugins should be disabled). To specify multiple plugins, separate them with a comma.
.TP
.B \-k PLUGNAME.PLUGOPT[=VALUE]
This is used to specify options for plugins. A list of available plugin options can be obtained from the output of --list-plugins.
If no value is specified and the option is a boolean (on/off), it will be set to "on".
.TP
.B \-a, \--alloptions
Enable all (boolean) options for all loaded plugins.
.TP
.B \-v, \--verbose
Increase the verbosity of the output as sosreport is running. Multiple -v mean more verbosity.
.TP
.B \--no-progressbar
Do not display a progress bar (ETA will not be available).
.TP
.B \--no-multithread
Disable multithreaded collection and analysis of the sosreport data.
.SH MAINTAINERS
.nf
Navid Sheikhol-Eslami <navid@redhat.com>
.fi
.SH AUTHORS
.nf
Steve Conklin <sconklin@redhat.com>
John Berninger <jwb@redhat.com>
Navid Sheikhol-Eslami <navid@redhat.com>
Pierre Amadio <pamadio@redhat.com>
.fi
