name: sosreport
summary: Sos is an extensible, portable, support data collection tool
description: |
  Sos is an extensible, portable, support data collection tool
  primarily aimed at Linux distributions and other UNIX-like operating
  systems.
grade: stable
base: core24
confinement: classic
adopt-info: sos
license: GPL-2.0-only
environment:
  PYTHONPATH: ${SNAP}/lib/python3.12/site-packages:${SNAP}/usr/lib/python3/dist-packages:${PYTHONPATH}

parts:
  sos:
    plugin: python
    source: .
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --always)"
    build-attributes:
      - enable-patchelf
    build-packages:
      - git
      - python3
      - gettext
      - python3-venv
    stage-packages:
      - python3.12-minimal
      - libpython3.12-minimal
      - libpython3.12-stdlib
    python-packages:
      - pip
      - setuptools
      - wheel
      - python_magic
      - packaging==24.0
      - boto3==1.26.155

apps:
  sos:
    command: bin/sos
