name: sosreport
summary: Sos is an extensible, portable, support data collection tool
description: |
  Sos is an extensible, portable, support data collection tool
  primarily aimed at Linux distributions and other UNIX-like operating
  systems.
grade: stable
base: core22
confinement: classic
adopt-info: sos

parts:
  sos:
    plugin: python
    source: .
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --always)"
    build-packages:
      - git
      - python3
      - snapcraft
      - gettext
    stage-packages:
      - python3-magic

apps:
  sos:
    environment:
      PYTHONPATH: ${PYTHONPATH}:${SNAP}/lib/python3.8/site-packages:${SNAP}/usr/lib/python3/dist-packages
    command: bin/sos
  sosreport:
    environment:
      PYTHONPATH: ${PYTHONPATH}:${SNAP}/lib/python3.8/site-packages:${SNAP}/usr/lib/python3/dist-packages
    command: bin/sos report
  sos-collector:
    environment:
      PYTHONPATH: ${PYTHONPATH}:${SNAP}/lib/python3.8/site-packages:${SNAP}/usr/lib/python3/dist-packages
    command: bin/sos collector
