name: Avocado

on:
  workflow_call:
    inputs:
      distro_image:
        required: true
        type: string
      distro_name:
        required: false
        type: string
      builds:
        required: true
        type: string
      test_name:
        required: true
        type: string
      stage_name:
        required: true
        type: string
      extra_script:
        required: false
        type: string
      can_fail:
        required: false
        type: boolean
        default: false
      foreman_ver:
        required: false
        type: string
      katello_ver:
        required: false
        type: string

jobs:
  test:
    name: ${{ inputs.stage_name }} Tests (${{ inputs.distro_name }}, ${{ matrix.build }})
    runs-on: ${{ inputs.distro_image == '' && inputs.distro_name || 'ubuntu-latest' }}
    continue-on-error: ${{ inputs.can_fail }}

    container:
      image: ${{ inputs.distro_image != '' && inputs.distro_image || null }}
      options: ${{ inputs.distro_image != '' && '--user root --privileged --cgroupns=host --tmpfs /tmp --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro' || '' }}

    env:
      FOREMAN_VER: ${{ inputs.foreman_ver }}
      KATELLO_VER: ${{ inputs.katello_ver }}
      DISTRO_NAME: ${{ inputs.distro_name }}

    strategy:
      matrix:
        build: ${{ fromJson(inputs.builds) }}

    steps:
      - name: Bootstrap DEB Container based OS
        if: ${{ contains(inputs.distro_name, 'debian') || ( contains(inputs.distro_name, 'ubuntu') && inputs.distro_image != '' ) }}
        run: |
          apt update
          apt -y install sudo

      - name: Bootstrap RPM based OS
        if: ${{ matrix.build == 'rpm' }}
        run: |
          dnf -y install sudo
          sed -i 's/^account.*pam_unix.so/account sufficient pam_permit.so/' /etc/pam.d/sudo
          sed -i 's/^account.*required.*pam_unix.so/account sufficient pam_permit.so/' /etc/pam.d/system-auth

      - name: Setup sudoers on containers
        if: ${{ inputs.distro_image != '' }}
        run: |
          CURRENT_USER=$(whoami)
          echo "Fixing sudo for user: $CURRENT_USER"

          mkdir -p /etc/sudoers.d
          echo "${CURRENT_USER} ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/gh-actions
          chmod 0440 /etc/sudoers.d/gh-actions

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          path: sos

      - name: Install functional test dependencies
        run: |
          if [ $(command -v apt) ]; then
            sudo apt update
            sudo apt -y install tox
            # Install packages required for testing
            sudo apt -y install kmod ethtool gnupg2 iproute2 procps curl wget
            [ $(echo "${{ inputs.distro_name }}" | grep ubuntu) ] && sudo apt -y install ubuntu-advantage-tools
          else
            dnf config-manager --set-enabled crb || true
            [ $( echo "${{ inputs.distro_name }}" | grep centos) ] && dnf -y install epel-release
            dnf -y install tox
            # Install packages required for testing
            dnf -y install kmod ethtool gnupg2 iproute hostname procps-ng file systemd
          fi
        continue-on-error: true

      - name: Enable systemd in containers
        if: ${{ matrix.build == 'rpm' || ( contains(inputs.distro_name, 'ubuntu') && inputs.distro_image != '' )}}
        run: |
          /usr/lib/systemd/systemd --user &

      - name: Download Distro-Specific DEB
        if: ${{ matrix.build == 'deb' }}
        uses: actions/download-artifact@v8
        with:
          name: sos-${{ env.DISTRO_NAME }}.deb

      - name: Download Distro-Specific RPM
        if: ${{ matrix.build == 'rpm' }}
        uses: actions/download-artifact@v8
        with:
          name: sos-${{ env.DISTRO_NAME }}.rpm

      - name: Download snap
        if: ${{ matrix.build == 'snap' }}
        uses: actions/download-artifact@v8
        with:
          name: sos-build.snap

      - name: Install the package
        run: |
          if [ $(command -v apt) ] ; then
            [ "$(dpkg -l sos)" ] && sudo apt -y purge sos ubuntu-server
            [ "$(dpkg -l sosreport)" ] && sudo apt -y purge sosreport ubuntu-server
          fi
          if [ "${{ matrix.build }}" == "deb" ] ; then
            sudo apt -y install ./"sos-${{ env.DISTRO_NAME }}.deb"
          elif [ "${{ matrix.build }}" == "snap" ] ; then
            sudo apt -y install snapd
            sudo snap install "sos-build.snap" --classic --dangerous
          elif [ "${{ matrix.build }}" == "rpm" ] ; then
            dnf -y remove sos
            dnf -y install "sos-${{ env.DISTRO_NAME }}.rpm"
          fi

      # This is primarily required for container systems
      - name: Pre-initialization of foreman test
        if: ${{ inputs.stage_name == 'foreman' && inputs.distro_image != '' }}
        run: |
          if [ $(command -v apt) ] ; then
            sudo apt -y install facter jq
          elif [ "${{ matrix.build }}" == "rpm" ] ; then
            dnf -y install facter jq
          fi
          FQDN=$(facter fqdn)
          SHORT=$(hostname -s)

          ip=$(ip -j -4 a show eth0 | jq -r '.[0].addr_info[0].local')

          cat > /etc/hosts << EOF
          127.0.0.1    localhost
          $ip    $FQDN $SHORT
          EOF

      - name: Run Extra script
        if: ${{ inputs.extra_script != '' }}
        working-directory: ./sos
        run: |
          sudo -E ${{ inputs.extra_script }}

      - name: Run Test Command
        working-directory: ./sos
        run: |
          sudo tox -e ${{ inputs.test_name }}

      - name: Prepare Root Logs for Upload
        if: failure()
        run: |
          ls -lh

          mkdir -p ./debug-logs/var-tmp
          mkdir -p ./debug-logs/root-home

          sudo cp -ra /var/tmp/avocado* ./debug-logs/var-tmp || true
          sudo cp -ra /root/avocado ./debug-logs/root-home || true

          sudo chown -R $USER:$USER ./debug-logs

      - name: Upload Distro Artifact
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: failure-logs-${{ env.DISTRO_NAME }}-${{ inputs.stage_name }}
          path: ./debug-logs/
          retention-days: 7

      - name: Post-Test Cleanup
        if: always()
        run: |
          # Clean up the downloaded deb and the synced tests repo
          rm -f *.deb *.snap *.rpm

          sudo apt-get purge -y sos || true
          sudo snap remove sosreport || true
          sudo dnf remove -y sos || true
