name: snap_strictmode
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: snap-strictmode-build
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        sudo cp snap/snapcraft_strictmode.yaml snapcraft.yaml
    - uses: snapcore/action-build@v1
      id: build-snap
    # Make sure the snap is installable
    - run: |
        sudo apt -y remove sosreport
        sudo snap install --devmode ${{ steps.build-snap.outputs.snap }}
        sudo snap alias sosreport.sos sos
    # Do some testing with the snap
    - run: |
        sudo sos help
    - uses: snapcore/action-publish@v1
      if: ${{ github.event_name == 'push' }}
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build-snap.outputs.snap }}
        release: "strictmode/edge"
    - uses: snapcore/action-publish@v1
      if: ${{ github.event_name == 'release' }}
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build-snap.outputs.snap }}
        release: "strictmode/beta"
