# This is a basic workflow to help you get started with Actions

name: 20.04 Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update; sudo apt install flake8 python3-pexpect
        
      - name: Flake8
        run: flake8 sos tests bin/*
        
      - name: Simple.sh
        run: sudo ./tests/simple.sh
        


#ubuntu-20.04
#Ubuntu 18.04	ubuntu-latest or ubuntu-18.04
#Ubuntu 16.04	ubuntu-16.04
